services:
  locket:
    image: ghcr.io/bpbradley/locket:op
    user: '65532:0'
    container_name: locket-agent-stack
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    command:
      - '--provider=op'
      # Park is needed otherwise when the continer exits it will remove the files creates in the tempfs volume
      - "--mode=park"
      - "--inject-failure-policy=error"
      - "--log-level=info"
      - "--user=65532:0"
      # -rw-r----- file mode
      - "--file-mode=0640"
      - "--dir-mode=0740"
      - '--op-token=file:/run/secrets/op_token'
      - '--secret=token=TOKEN={{ op://DockerSecrets/dockhand/rpi-token }}'
    secrets:
      - op_token
    volumes:
      - secrets-store-agent:/run/secrets/locket

  hawser:
    container_name: hawser-rpi
    restart: unless-stopped
    image: ghcr.io/finsys/hawser:latest
    # Override the default entrypoint to load the token from the secret file into an environment variable without writing
    # them to disk, then exec the original entrypoint
    enterypoint: ["/init.sh", "-f", "/run/secrets/locket/token"]
    command: ["/usr/local/bin/hawser"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/stacks:/opt/stacks
      - secrets-store-agent:/run/secrets/locket:ro
    environment:
      - TZ=America/Chicago
      - STACKS_DIR=/opt/stacks
      - PORT=2376
      - AGENT_NAME=rpi
    ports:
      - 2376:2376
    labels:
      - dockhand.update=false

  hawser-updater:
    image: docker:24-cli
    container_name: hawser-updater
    restart: 'no'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/host/hawser:ro
    working_dir: /host/hawser
    entrypoint: >
      sh -c "
        echo 'Pulling latest Hawser image...';
        docker compose pull hawser;
        echo 'Recreating Hawser container...';
        docker compose up -d hawser;
        echo 'Done.';
      "

secrets:
  op_token:
    file: /etc/op/token

volumes:
  secrets-store-agent:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: uid=65532,gid=1000,mode=740
