services:
  locket:
    image: ghcr.io/bpbradley/locket:op
    user: "65532:0"
    container_name: locket-proxy
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    command:
      - "--provider=op"
      # one-shot removes the secrets before they can be imported switching to park.
      - "--mode=park"
      - "--inject-failure-policy=error"
      - "--log-level=info"
      - "--user=65532:0"
      # -r--r--r-- file mode
      - "--file-mode=0664"
      - "--dir-mode=0777"
      - "--op-token=file:/run/secrets/op_token"
      - "--secret=tunnel_token={{ op://DockerSecrets/Proxy-config/cf-token }}"
      - "--map=/caddy:/run/secrets/locket/caddy"
    secrets:
      - op_token
    volumes:
      # Mount in your actual secret templates, with secret references
      - ./config/caddy:/caddy:ro
      # Mount in your output directory, where you want secrets materialized
      - secrets-store-proxy:/run/secrets/locket

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest # Pull the latest version of the Cloudflare Tunnel image
    container_name: cloudflare-tunnel # Name of the Cloudflare Tunnel container
    hostname: cloudflare-tunnel # Hostname for the Cloudflare Tunnel container
    restart: unless-stopped # Restart the container unless manually stopped
    depends_on:
      locket:
        condition: service_healthy
      caddy:
        condition: service_started
    command: tunnel run # Command to start the Cloudflare tunnel
    volumes:
      - /etc/localtime:/etc/localtime:ro # Synchronize time with the host
      - type: volume
        source: secrets-store-proxy
        target: /run/secrets/tunnel_token
        read_only: true
        volume:
          subpath: tunnel_token
    environment:
      - "TUNNEL_TOKEN_FILE=/run/secrets/tunnel_token" # Pass the Cloudflare Tunnel token from environment variable
    healthcheck:
      test: ["CMD", "cloudflared", "--version"] # Check if cloudflared version command works
      interval: 30s # Time between health check attempts
      timeout: 10s # Time to wait for a response
      retries: 3 # Number of retries before marking as unhealthy
      start_period: 10s # Delay before health checks begin # Enable automatic updates with Watchtower

  caddy:
    build:
      context: .
      dockerfile_inline: |
        # Stage 1: Build Caddy with custom modules using xcaddy
        FROM caddy:2-builder AS builder
        # bouncer 2 https://app.crowdsec.net/hub/author/hslatman/remediation-components/caddy-crowdsec-bouncer
        RUN xcaddy build \
            --with github.com/caddy-dns/cloudflare \
            --with github.com/kassner/caddy-trapdoor \
            --with github.com/mholt/caddy-l4 \
            --with github.com/caddyserver/transform-encoder \
            --with github.com/hslatman/caddy-crowdsec-bouncer/http@main \
            --with github.com/hslatman/caddy-crowdsec-bouncer/appsec@main \
            --with github.com/hslatman/caddy-crowdsec-bouncer/layer4@main
        # Stage 2: Create the final lightweight image
        FROM caddy:2
        # Copy the custom compiled binary from the builder stage
        COPY --from=builder /usr/bin/caddy /usr/bin/caddy
    restart: unless-stopped
    container_name: caddy-reverse-proxy
    depends_on:
      locket:
        condition: service_healthy
    cap_add:
      - NET_ADMIN
    expose:
      - 80
      - 443
      - 443/udp
    volumes:
      - type: volume
        source: secrets-store-proxy
        target: /etc/caddy
        volume:
          subpath: caddy
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - default
      - proxy

  #https://docs.crowdsec.net/u/getting_started/installation/docker
  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec-proxy
    restart: always
    expose:
      - 8080
    environment:
      COLLECTIONS:
      GID: 1000
      UID: 1000
      TZ: America/Chicago
    volumes:
      - ./config/crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - crowdsec-db:/var/lib/crowdsec/data/
      - crowdsec-config:/etc/crowdsec/
    networks:
      - default
      - logging-network

#  bouncer1:
#https://app.crowdsec.net/hub/author/Teifun2/remediation-components/cs-unifi-bouncer
#    image: ghcr.io/teifun2/cs-unifi-bouncer
#    container_name: unifi-bouncer
#    enviroment:
#      UNIFI_POLICY_REORDERING: true
#      UNIFI_LOG_CLEANUP: true
#      ENABLE_METRICS: true

secrets:
  op_token:
    file: /etc/op/token

networks:
  default: {}
  proxy:
    external: true
  logging-network:
    external: true

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  crowdsec-db:
    driver: local
  crowdsec-config:
    driver: local
  secrets-store-proxy:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: uid=65532,gid=0,mode=760
