services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    expose:
      - 8080
    networks:
      - proxy
networks:
  proxy:
    external: true
      
