apiVersion: 1
datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true

  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    version: Flux
    isDefault: false
    jsonData:
      organization: myorg
    secureJsonData:
      token: influx-token
