apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    version: Flux
    isDefault: false
    jsonData:
      organization: myorg
    secureJsonData:
      token: influx-token
      
  - name: Victoria Logs
    type: prometheus
    