# route requests between VictoriaMetrics and VictoriaLogs
unauthorized_user:
  url_map:
    - src_paths: ["/vm/.*"]
      drop_src_path_prefix_parts: 1
      url_prefix: http://victoriametrics:8428
    - src_paths: ["/vl/.*"]
      drop_src_path_prefix_parts: 1
      url_prefix: http://victorialogs:9428
    - src_paths: ["/grafana.*"]
      url_prefix: http://grafana:3000
    - src_paths: ["/.*"]
      url_prefix: http://victorialogs:9428/select/vmui
users:
  - username: "op://DockerSecrets/logging-stack/docker_user"
    password: "op://DockerSecrets/logging-stack/docker_password"
    url_map:
      - src_path: ["/.*"]
        drop_src_path_prefix_parts: 1
        url_prefix: http://victorialogs:9428/insert/loki/api/v1/push
  - username: "op://DockerSecrets/logging-stack/vector_user"
    password: "op://DockerSecrets/logging-stack/vector_password"
    url_map:
      - src_path: ["/.*"]
        drop_src_path_prefix_parts: 1
        url_prefix: http://victorialogs:9428/insert/jsonline