# Working correctly
# need to make sure security is good still.
services:
  locket:
    image: ghcr.io/bpbradley/locket:op
    # OP complains about file permissions if it doesnt have 65532 user or group.
    user: "65532:1000"
    container_name: locket-dockhand
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    command:
      - "--provider=op"
      # Park is needed otherwise when the continer exits it will remove the files creates in the tempfs volume
      - "--mode=park"
      - "--inject-failure-policy=error"
      - "--log-level=info"
      - "--user=65532:1000"
      # -rw-r----- file mode
      - "--file-mode=0640"
      - "--dir-mode=0740"
      - "--op-token=file:/run/secrets/op_token"
      - "--secret=encryption_key=ENCRYPTION_KEY={{ op://DockerSecrets/dockhand/encryption_key }}"
      # --secret=file name=file contents
    secrets:
      - op_token
    volumes:
      - secrets-store-dockhand:/run/secrets/locket

  socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: socket-proxy
    restart: unless-stopped
    logging:
      driver: "none"
    environment:
      # Required for Dockhand core functionality
      - CONTAINERS=1
      - IMAGES=1
      - NETWORKS=1
      - VOLUMES=1
      - EVENTS=1
      - POST=1
      - DELETE=1
      # Required for dashboard host info and disk usage
      - INFO=1
      - SYSTEM=1
      # Required for vulnerability scanning
      - ALLOW_START=1
      - ALLOW_STOP=1
      - ALLOW_RESTARTS=1
      # Optional: enable for terminal access
      # - EXEC=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket-proxy

  # TODO: Need to look about a config file that can have enviroments added by code.
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    depends_on:
      locket:
        condition: service_healthy
      socket-proxy:
        condition: service_started
    restart: unless-stopped
    # Override the default entrypoint to load the encryption key from the secret file into an environment variable without writing
    # them to disk, then exec the original entrypoint
    # https://github.com/Finsys/dockhand/blob/main/Dockerfile
    entrypoint:
      [
        "/sbin/tini",
        "--",
        "/init.sh",
        "-f",
        "/run/secrets/locket/encryption_key",
      ]
    command: ["/usr/local/bin/docker-entrypoint.sh"]
    ports:
      - 3000:3000
    volumes:
      - ../../common/scripts/init.sh:/init.sh:ro
      - secrets-store-dockhand:/run/secrets/locket:ro
      - /opt/dockhand:/opt/dockhand
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DATA_DIR=/opt/dockhand
      - HOST_DATA_DIR=/opt/dockhand
    networks:
      - socket-proxy
      - default
      - proxy

secrets:
  op_token:
    file: /etc/op/token

volumes:
  secrets-store-dockhand:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: uid=65532,gid=1000,mode=740
networks:
  socket-proxy:
    internal: true
  proxy:
    external: true
