services:
  locket:
    image: ghcr.io/bpbradley/locket:op
    user: '65532:65532'
    container_name: locket-auth
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
  command:
    - '--provider=op'
    - '--mode=exit'
    - '--inject-failure-policy=error'
    - '--op-token=file:/run/secrets/op_token'
    - '--map=/config:/run/secrets/locket/kopia'
  secrets:
    - op_token
  volumes:
    # Mount in your actual secret templates, with secret references
    - ./config:/config:ro
      # Mount in your output directory, where you want secrets materialized
    - secrets-store-auth:/run/secrets/locket
  kopia:
    image: kopia/kopia:latest
    hostname: kopia
    container_name: Kopia
    restart: unless-stopped
    entrypoint: ["init.sh -f /run/secrets/locket/kopia/secrets.env"]
    command: ["/bin/kopia"]
    ports:
      - 51515:51515
    # Setup the server that provides the web gui
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:51515
      - --server-username=${USER}
      - --server-password=${KOPIA_PASSWORD}
    environment:
      KOPIA_PASSWORD: ${REPO_PASSWORD}
      USER: ${REPO_USER}
    volumes:
      # Mount local folders needed by kopia
      - /mnt/thehub/Data/kopia/config:/app/config
      - /mnt/thehub/Data/kopia/cache:/app/cache
      - /mnt/thehub/Data/kopia/logs:/app/logs
      # Mount local folders to snapshot
      - /mnt/thehub/Data/ampBackups:/data/amp:ro
      - /mnt/thehub/Data/Code:/data/code:ro
      - /mnt/thehub/Data/proxmoxBackups:/data/proxmox:ro
      - '/mnt/thehub/Data/Evos Data:/data/evo:ro'
      - /mnt/thehub/Data/haledata:/data/haledata:ro
      - /mnt/thehub/Data/mcgeedata:/data/mcgeedata:ro
      - /mnt/thehub/Data/scottsdata:/data/scottsdata:ro
      # Mount repository location
      - /mnt/thehub/Data/kopia/repo:/repository
      # Mount path for browsing mounted snapshots
      - /mnt/thehub/Data/tmp:/tmp:shared
