# upsmon.conf - Network UPS Tools monitor configuration

# Specify the user upsmon should run as
RUN_AS_USER root

# Monitor a UPS unit
# MONITOR <upsname>@<hostname> <power_value> <username> <password> <type>
# TODO: Add op:// for user and password
MONITOR ups@ip 1  secondary

POLLFREQ 2
POLLFREQALERT 1
SHUTDOWNCMD "/sbin/shutdown -h"

# Notifications
# NOTIFYCMD <command>
NOTIFYCMD /usr/sbin/upssched

# Notification messages for syslog
NOTIFYMSG ONLINE    "UPS %s on line power"
NOTIFYMSG ONBATT    "UPS %s on battery"
NOTIFYMSG LOWBATT   "UPS %s battery is low"
NOTIFYMSG FSD       "UPS %s: forced shutdown in progress"
NOTIFYMSG COMMOK    "Communications with UPS %s established"
NOTIFYMSG COMMBAD   "Communications with UPS %s lost"
NOTIFYMSG SHUTDOWN  "Auto logout and shutdown proceeding"
NOTIFYMSG REPLBATT  "UPS %s battery needs to be replaced"
NOTIFYMSG NOCOMM    "UPS %s is unavailable"
NOTIFYMSG NOPARENT  "upsmon parent process died - shutdown impossible"


# NOTIFYFLAG <event> <flags>
NOTIFYFLAG ONLINE SYSLOG+WALL+EXEC
NOTIFYFLAG ONBATT SYSLOG+WALL+EXEC
NOTIFYFLAG LOWBATT SYSLOG+WALL+EXEC
NOTIFYFLAG FSD SYSLOG+WALL+EXEC
NOTIFYFLAG COMMBAD SYSLOG+WALL+EXEC
NOTIFYFLAG COMMOK SYSLOG+WALL+EXEC
NOTIFYFLAG SHUTDOWN SYSLOG+WALL+EXEC
NOTIFYFLAG REPLBATT SYSLOG+WALL+EXEC
NOTIFYFLAG NOCOMM SYSLOG+WALL+EXEC

# Delay before shutdown after a low battery event
FINALDELAY 5

# How long to wait for UPS to come back online after a communication loss
HOSTSYNC 15
