CMDSCRIPT /etc/nut/upssched.sh
PIPEFN /etc/nut/upssched.pipe
LOCKFN /etc/nut/upssched.lock

AT ONBATT * START-TIMER onbatt 5
AT ONBATT * START-TIMER fsdtimer 1200
AT ONLINE * CANCEL-TIMER onbatt online
AT ONLINE * CANCEL-TIMER fsdtimer online
AT LOWBATT * EXECUTE shutdowncritical
AT COMMBAD * START-TIMER commbad 45
AT COMMOK * CANCEL-TIMER commbad commok
AT NOCOMM * START-TIMER commbad 45
AT SHUTDOWN * EXECUTE powerdown
AT REPLBATT * EXECUTE battbad