# TODO:
# test postgress with the custom entery script
# make sure the file persmisions works will all the services or if they need to be setup in the compose
services:
  locket:
    image: ghcr.io/bpbradley/locket:op
    user: "65532:1000"
    container_name: locket-auth
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    command:
      - "--provider=op"
      # one-shot removes the secrets before they can be imported switching to park.
      - "--mode=park"
      - "--inject-failure-policy=error"
      - "--log-level=info"
      - "--user=65532:1000"
      # -rw-r----- file mode
      - "--file-mode=0777"
      - "--dir-mode=0777"
      - "--op-token=file:/run/secrets/op_token"
      - "--map=/authelia:/run/secrets/locket/authelia"
      - "--map=/lldap:/run/secrets/locket/lldap"
      - "--map=/postgres:/run/secrets/locket/postgres"
    secrets:
      - op_token
    volumes:
      # Mount in your actual secret templates, with secret references
      - ./config/authelia:/authelia:ro
      - ./config/lldap:/lldap:ro
      - ./config/postgres:/postgres:ro
      # Mount in your output directory, where you want secrets materialized
      - secrets-store-auth:/run/secrets/locket

  authelia-db:
    image: postgres:18.4
    depends_on:
      locket:
        condition: service_healthy
    container_name: authdb
    # Override the default entrypoint to run our init script first, which will populate the environment variables from the secrets without
    # writing them to disk, then exec the original entrypoint
    # https://github.com/docker-library/postgres/blob/master/15/alpine3.24/Dockerfile
    entrypoint: ["/init.sh", "-f", "/config/.env"] # works
    command: ["docker-entrypoint.sh", "postgres"] # get error about this script not found?
    expose:
      - 5432
    restart: unless-stopped
    volumes:
      - type: bind
        source: ../../common/scripts/init.sh
        target: /init.sh
        read_only: true
      - type: volume
        source: secrets-store-auth
        target: /config
        read_only: true
        volume:
          subpath: postgres
      - type: volume
        source: authdb-git
        target: /var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "$${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  lldap:
    image: lldap/lldap:stable-alpine-rootless
    depends_on:
      locket:
        condition: service_healthy
    container_name: lldap
    # change config location default
    command: ["run", "--config-file", "/config/lldap_config.toml"]
    expose:
      - 3890
      - 17170
    restart: unless-stopped
    volumes:
      - type: volume
        source: lldap-git
        target: /data
      - type: volume
        source: secrets-store-auth
        target: /config
        read_only: true
        volume:
          subpath: lldap
    environment:
      UID: 1000
      GID: 1000
      TZ: America/Chicago
    networks:
      - default
      - proxy
    healthcheck:
      test:
        [
          "CMD",
          "/app/lldap",
          "healthcheck",
          "--config-file",
          "/config/lldap_config.toml",
        ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  authelia:
    image: authelia/authelia:latest
    depends_on:
      locket:
        condition: service_healthy
      authelia-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      lldap:
        condition: service_healthy
    container_name: authelia
    expose:
      - 9091
    restart: unless-stopped
    volumes:
      - type: volume
        source: secrets-store-auth
        target: /config
        read_only: false
        volume:
          subpath: authelia
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
      X_AUTHELIA_CONFIG_FILTERS: template
    networks:
      - default
      - proxy

  redis:
    image: redis:alpine
    container_name: redisauthelia
    volumes:
      - redis-git:/data
    expose:
      - 6379
    restart: unless-stopped
    environment:
      TZ: America/Chicago
      PUID: 1000
      PGID: 1000
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default: {}
  proxy:
    external: true

secrets:
  op_token:
    file: /etc/op/token

volumes:
  redis-git:
    driver: local
  lldap-git:
    driver: local
  authdb-git:
    driver: local
  secrets-store-auth:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: uid=65532,gid=1000,mode=740
