services:
  locket:
    image: ghcr.io/bpbradley/locket:op
    user: "65532:0"
    container_name: locket-logs
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    command:
      - "--provider=op"
      # one-shot removes the secrets before they can be imported switching to park.
      - "--mode=park"
      - "--inject-failure-policy=error"
      - "--log-level=info"
      - "--user=65532:0"
      # -r--r--r-- file mode
      - "--file-mode=0444"
      - "--dir-mode=0755"
      - "--op-token=file:/run/secrets/op_token"
      - "--secret=grafana_domain={{ op://DockerSecrets/logging-stack/grafana-domain }}"
      - "--secret=grafana_domain_base={{ op://DockerSecrets/logging-stack/grafana-domain-base }}"
      - "--map=/vmauth:/run/secrets/locket/vmauth"
    secrets:
      - op_token
    volumes:
      # Mount in your actual secret templates, with secret references
      - ./config/vmauth:/vmauth:ro
      # Mount in your output directory, where you want secrets materialized
      - secrets-store-logs:/run/secrets/locket

  # Grafana instance configured with VictoriaLogs as datasource
  grafana:
    image: grafana/grafana:12.4.5
    depends_on:
      locket:
        condition: service_healthy
      victorialogs:
        condition: service_started
      victoriametrics:
        condition: service_started
    expose:
      - 3000
    volumes:
      - type: volume
        source: secrets-store-logs
        target: /run/secrets/grafana_domain
        read_only: true
        volume:
          subpath: grafana_domain
      - type: volume
        source: secrets-store-logs
        target: /run/secrets/grafana_domain_base
        read_only: true
        volume:
          subpath: grafana_domain_base
      - grafanadata:/var/lib/grafana
      - ./config/grafana/provisioning/datasources/single.yml:/etc/grafana/provisioning/datasources/single.yml
      - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./config/grafana/dashboards/victorialogs.json:/var/lib/grafana/dashboards/victorialogs.json
      - ./config/grafana/dashboards/victorialogs-internal.json:/var/lib/grafana/dashboards/victorialogs-internal.json
    environment:
      - "GF_INSTALL_PLUGINS=victoriametrics-logs-datasource"
      - "GF_SERVER_DOMAIN__FILE=/run/secrets/grafana_domain"
      - "GF_SERVER_ROOT_URL__FILE=/run/secrets/grafana_domain_base"
      - "GF_SERVER_SERVE_FROM_SUB_PATH=true"
      - "GF_AUTH_DISABLE_LOGIN_FORM=true"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
    restart: always
    networks:
      - default
      - proxy

  #  VictoriaLogs instance, a single process responsible for
  #  storing logs and serving read queries.
  victorialogs:
    image: victoriametrics/victoria-logs:v1.51.0
    ports:
      - 9428
    command:
      - "-storageDataPath=/vlogs"
      - "-retentionPeriod=100y"
      - "-retention.maxDiskUsagePercent=35"
    volumes:
      - vldata:/vlogs
    restart: always

  # VictoriaMetrics instance, a single process responsible for
  # scraping, storing metrics and serve read requests.
  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.146.0
    expose:
      - 8428
    volumes:
      - vmdata:/storage
      - ./config/victoriametrics/prometheus-vl-single.yml:/etc/prometheus/prometheus.yml
    command:
      - "--storageDataPath=/storage"
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--vmalert.proxyURL=http://vmalert:8880"
    restart: always

  # vmauth is a router and balancer for HTTP requests.
  # It proxies query requests from vmalert to either VictoriaMetrics or VictoriaLogs,
  # depending on the requested path.
  vmauth:
    image: victoriametrics/vmauth:v1.146.0
    depends_on:
      locket:
        condition: service_healthy
      victorialogs:
        condition: service_started
      victoriametrics:
        condition: service_started
    volumes:
      - type: volume
        source: secrets-store-logs
        target: /config
        read_only: true
        volume:
          subpath: vmauth
    command:
      - "--auth.config=/config/config.yml"
    expose:
      - 8427
    restart: always
    networks:
      - default
      - proxy

  # vmalert executes alerting and recording rules according to the given rule type.
  vmalert:
    image: victoriametrics/vmalert:v1.146.0
    depends_on:
      - "vmauth"
      - "alertmanager"
      - "victoriametrics"
    expose:
      - 8880
    volumes:
      - ./config/vmalert/rules/alerts-vlogs.yml:/etc/alerts/vlogs.yml
      - ./config/vmalert/rules/alerts-health.yml:/etc/alerts/alerts-health.yml
      # vlogs rule
      - ./config/vmalert/vlogs-example-alerts.yml:/etc/alerts/vlogs-example-alerts.yml
    command:
      # it evaluates data against VictoriaMetrics and VictoriaLogs
      # vmauth routes queries to corresponding datasource based on API path
      - "--datasource.url=http://vmauth:8427/"
      # results of alerting and recording rules are persisted to VictoriaMetrics only
      - "--remoteWrite.url=http://victoriametrics:8428/"
      # alerts state is restored from VictoriaMetrics on restarts
      - "--remoteRead.url=http://victoriametrics:8428/"
      - "--notifier.url=http://alertmanager:9093/"
      - "--rule=/etc/alerts/*.yml"
      # display source of alerts in grafana
      - "--external.url=http://127.0.0.1:3000" #grafana outside container
      - '--external.alert.source=explore?orgId=1&left={"datasource":"{{ if eq .Type "vlogs" }}VictoriaLogs{{ else }}VictoriaMetrics{{ end }}","queries":[{"expr":{{.Expr|jsonEscape|queryEscape}},"refId":"A"}],"range":{"from":"{{ .ActiveAt.UnixMilli }}","to":"now"}}'
    restart: always

  # alertmanager receives alerting notifications from vmalert
  # and distributes them according to --config.file.
  alertmanager:
    image: prom/alertmanager:v0.33.0
    volumes:
      - ./config/alertmanager/alertmanager.yml:/config/alertmanager.yml
    command:
      - "--config.file=/config/alertmanager.yml"
    expose:
      - 9093
    restart: always

networks:
  default: {}
  proxy:
    external: true

secrets:
  op_token:
    file: /etc/op/token

volumes:
  vmdata: {}
  vldata: {}
  grafanadata: {}
  secrets-store-logs:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: uid=65532,gid=1000,mode=744
